### ISSUE TITLE
Error: Could not find a suitable provider for cpanm

### ISSUE THREAD

**Issue by digiisoft** [jamesmcdonald/puppet-cpanm#4]
Centos 7 & Puppet v4.10.5

```
  cpanm { 'CGI':
    ensure => latest,
  }
```
Gives me this error...
```
==> default: Debug: Puppet::Type::Cpanm::ProviderDefault: file cpanm does not exist
==> default: Debug: Class[Site_legacy::Smppg]: Resource is being skipped, unscheduling all events
==> default: Info: Class[Site_legacy::Smppg]: Unscheduling all events on Class[Site_legacy::Smppg]
==> default: Debug: Stage[main]: Resource is being skipped, unscheduling all events
==> default: Error: Could not find a suitable provider for cpanm
```

Any help is appreciated.  Thanks for writing the module.

Chris

**Comment by jamesmcdonald** [comment]
Did you also `include cpanm`? You need the class included to set things up.

**Comment by digiisoft** [comment]
Yes, I did include cpanm.

--

Chris Edwards

On Jul 3, 2018, at 3:39 AM, James McDonald <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you also include cpanm? You need the class included to set things up.

**Comment by jamesmcdonald** [comment]
Hmm, that's strange. I can reproduce your exact error with the manifest:

```
cpanm {'CGI':
    ensure => latest,
}
```

But it works properly if I change it to:

```
include cpanm

cpanm {'CGI':
    ensure => latest,
}
```

Do you have any other errors that could suggest something is wrong with the cpanm installation process? On a fresh CentOS 7 for me it installs `gcc` and `perl-core`, creates the bootstrap in `/var/cache` and then runs `/usr/bin/perl /var/cache/cpanm-install  -n App::cpanminus`.

**Comment by jamesmcdonald** [comment]
It's possible that your Puppet process (agent/apply) is being run with a `PATH` that doesn't include the location your perl installs `cpanm` to. By default it is installed to `/usr/local/bin` on CentOS 7.

**Comment by digiisoft** [comment]
Thats the problem.  /usr/local/bin is not in my root PATH.  Not sure how to fix this.

**Comment by jamesmcdonald** [comment]
That's tricky to give a general answer to. It depends on how you are running Puppet and how your system has been set up. The default CentOS 7 install has `/usr/local/bin` in `$PATH` for both shells and systemd services, so something on your setup is probably modified.

If you're experiencing this problem while running Puppet directly, it's likely there's a `PATH` override in your bash profile (or zsh, or...); if the problem is happening with the system Puppet agent service then there's probably a `PATH` setting in the service configuration (for example `/etc/sysconfig/puppet` or the actual systemd unit files). You can hopefully fix it by setting the default `PATH` in the appropriate location, which looks to be `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin`.

Hope that helps track down the problem.
